### ISSUE TITLE
Capture Marital Status

### ISSUE THREAD

**Issue by cragun47** [LinuxForHealth/hl7v2-fhir-converter#103]
**Describe the bug**
Add capability to find and convert the following patient information

- Patient.maritalStatus / PID-16

>NOTE: this was moved from #94 

**To Reproduce**
Create a sample HL7V2.6 patient PID segment with aforementioned patient information.

**Expected behavior**
Patient information should be detected and added to corresponding fields in HL7 FHIR resources.

**Screenshots**
N/A

**Desktop (please complete the following information):**
 - OS:  Mac OS 
 - Version Big Sur

**Additional context**

Information about [HL7V2.6 codes](https://hl7-definition.caristix.com/v2/HL7v2.6/Tables/0002)
Information about [HL7 FHIR codes](https://www.hl7.org/fhir/valueset-marital-status.html)
Tasks:
Create an addition to `Patient.yml`
Create a Utility in `Hl7RelatedGeneralUtils.java` to support the changes to `Patient.yml`.  `getAddressUse` is a good pattern to follow.
Create a unit test for the utility you created. `test_getAddressUse` is a good pattern to follow.
Create or enhance an existing unit test with a patient in `src/test/java/io/github/linuxforhealth/hl7/segments/Hl7PatientFHIRConversionTest.java`

**Comment by LisaWellman** [comment]
In Release 1.0.9
