### ISSUE TITLE
HL7 message without including Patient.gender info (blank PID-8 field) fails to convert

### ISSUE THREAD

**Issue by claverols** [LinuxForHealth/hl7v2-fhir-converter#105]
**Describe the bug**
An HL7 message without including the patient's gender info (blank PID-8 field) fails to convert. 
This field is optional (Cardinality 0..1 in FHIR 4.0 reference and according to the HL7 reference as well), thus it should convert into a JSON file.

**To Reproduce**
I tried to convert sample_unix.hl7 included in the converter (under src/test/resources) after having removed the gender info from it (|F|), so the PID segment became: 

PID|0010||PID1234^5^M11^A^MR^HOSP~1234568965^^^USA^SS||DOE^JOHN^A^||19800202|||W|111 TEST_STREET_NAME^^TEST_CITY^NY^111-1111^USA||(905)111-1111|||S|ZZ|12^^^124|34-13-312||||TEST_BIRTH_PLACE

I ran the current HL7toFHIR converter on the edited sample_unix.hl7 and I got the error below:
ca.uhn.fhir.parser.DataFormatException: [element=“gender”] Invalid attribute value “?”: Unknown AdministrativeGender code ‘?’
	at ca.uhn.fhir.parser.StrictErrorHandler.invalidValue(StrictErrorHandler.java:50)
	at ca.uhn.fhir.parser.LenientErrorHandler.invalidValue(LenientErrorHandler.java:90)
	at ca.uhn.fhir.parser.ParserState$PrimitiveState.attributeValue(ParserState.java:1350)
...
**Expected behavior**
I would expect the HL7 message to convert without that error, as the gender field is optional.

**Desktop (please complete the following information):**
 - OS: Mac OS
 - Version Big Sur

**Comment by LisaWellman** [comment]
In Release 1.0.9
