### ISSUE TITLE
Improve patient name field capture

### ISSUE THREAD

**Issue by cragun47** [LinuxForHealth/hl7v2-fhir-converter#108]
**Describe the bug**
Add capability to find and convert the following patient information

- Patient.name.use / PID-5.7
- Patient.name.given / PID-5.3 (middle name) 

>NOTE: moved from #94

**To Reproduce**
Create a sample HL7V2.6 patient PID segment with aforementioned patient information.

**Expected behavior**
Patient information should be detected and added to corresponding fields in HL7 FHIR resources.

**Screenshots**
N/A

**Comment by LisaWellman** [comment]
In Release 1.0.9
