### ISSUE TITLE
Capture patient's mother's maiden name and religion

### ISSUE THREAD

**Issue by cragun47** [LinuxForHealth/hl7v2-fhir-converter#109]
**Describe the bug**
Create FHIR Patient.extension.patient-mothersMaidenName (well-known extension) from PID-6.1

Create FHIR Patient.extension.patient-religion (well-known extension) from PID-17, use coding in table 0006

**To Reproduce**
Create a sample HL7V2.6 patient PID segment with aforementioned patient information.

**Expected behavior**
Patient information should be detected and added to corresponding fields in HL7 FHIR resources.

Example FHIR for mother's maiden name:
```
extension": [
 {
    "url": "http://hl7.org/fhir/StructureDefinition/patient-mothersMaidenName",
    "valueString": "BEILY"
 }
```

Example FHIR for religion:
```
      "extension": [ {
        "url": "http://hl7.org/fhir/StructureDefinition/patient-religion",
        "valueCodeableConcept": {
          "coding": [ {
            "system": "http://terminology.hl7.org/CodeSystem/v3-ReligiousAffiliation",
            "code": "1028",
            "display": "Lutheran"
          } ],
          "text": "Lutheran"
        }
      }
```

**Additional context**
Religion in HL7 V2.6 is from [table 0006](https://hl7-definition.caristix.com/v2/HL7v2.6/Tables/0006). It does not have a perfect correlation to FHIR extension for [religion](https://www.hl7.org/fhir/v3/ReligiousAffiliation/vs.html)  Map clear matches from V2.6 to FHIR, but be conservative in a first pass, and unclear matches should be left unmatched.

**Comment by LisaWellman** [comment]
In Release 1.0.9
