### ISSUE TITLE
Capture Patient Telcom information

### ISSUE THREAD

**Issue by cragun47** [LinuxForHealth/hl7v2-fhir-converter#110]
**Describe the bug**
Add capability to find and convert the following patient information

- Patient.telecom / PID-13 (home), PID-14 (work)
Moved from #94  

**To Reproduce**
Create a sample HL7V2.6 patient PID segment with aforementioned patient information.

**Expected behavior**
Patient information should be detected and added to corresponding fields in HL7 FHIR resources.

Examples:

Telcom (both home and work):  follow the [Extended Telephone Communication XTN](https://hl7-definition.caristix.com/v2/HL7v2.6/DataTypes/XTN) format  (should allow for multiple)

```
  "telecom": [
    {
      "system": "phone",
      "value": "(203) 555 6473",
      "use": "home",
      "rank": 1
    },
    {
      "system": "phone",
      "value": "(203) 555 6473",
      "use": "work",
    }
    }
  ],
```

The following references PID.13, but the same applies to PID.14, or anything of type XTN
1. Logic for what Data to put into ContactPoint.value:
Use 13.5, 13.6, and 13.7 if 13.7 if not blank
else use 13.12 if not blank
else use 13.1 if not blank
    1. We will not check if these fields have inconsistent information, but use the first one that has data
1. Format of data in ContactPoint.value:
    1. if using 13.5, 13.6, 13.7, and 13.5 is not blank, format like this:
          `(607) 123 4567`
    1. if using 13.5, 13.6, 13.7, and 13.5 is blank, format like this:
	  `+22 607 123 4567`
    1. Otherwise take the value as it is (do not alter the format)
1. We will not use the FHIR extensions at https://build.fhir.org/ig/HL7/v2-to-fhir/ConceptMap-datatype-xtn-to-contactpoint.html
1. Use 13.18 Preference Order as the rank.
2. If 13.3 is "CP" then set  Patient.telecom.use to "mobile" and Patient.telecom.system to "phone"

**Screenshots**
N/A

**Additional context**

**Comment by LisaWellman** [comment]
In Release 1.0.9
