### ISSUE TITLE
Capture patient preferred language

### ISSUE THREAD

**Issue by cragun47** [LinuxForHealth/hl7v2-fhir-converter#111]
**Describe the bug**
Add capability to find and convert the following patient information

- Patient.communication.language, Patient.communication.preferred / PID-15
(Moved from #94)

**To Reproduce**
Create a sample HL7V2.6 patient PID segment with aforementioned patient information.

**Expected behavior**
Patient information should be detected and added to corresponding fields in HL7 FHIR resources.

Examples:

Communication language:  recommended based on ISO table 639. However ISO 639 has additional versions.  This is a [CWE encoding.](https://hl7-definition.caristix.com/v2/HL7v2.6/Fields/PID.15)

```
  "communication": [
    {
      "language": {
        "coding": [
          {
            "system": "urn:ietf:bcp:47",  << May not be this system.
            "code": "nl",
            "display": "Dutch"
          }
        ],
        "text": "Nederlands"
      },
      "preferred": true
    }
  ],
```

**Screenshots**
N/A

**Additional context**

**Comment by LisaWellman** [comment]
In Release 1.0.9
