### ISSUE TITLE
Add support for patient email

### ISSUE THREAD

**Issue by cragun47** [LinuxForHealth/hl7v2-fhir-converter#131]
Add support for patient email to telecom

If PID.13 (home) or PID.14 (work) has a value in XTN.4 create a ContactPoint element.
Example:
```json
{
        "system": "email",
        "value": "impatient@themail.com",
        "use": "home",   
        "rank": 1
      }
```

-  **use** will be "home" for PID.13, "work" for PID.14
-  **rank** will be included if there is a value in XTN.18

At this time, no need to check if XTN.2 has NET or XTN.3 has Internet or X.400.  Although these would be expected. If there is any value in email, we will capture it.  In the future if validation of email format is required, it can be added.

**Comment by LisaWellman** [comment]
In Release 1.0.9
