### ISSUE TITLE
Do not assume multiple births unless explicitly stated.

### ISSUE THREAD

**Issue by cragun47** [LinuxForHealth/hl7v2-fhir-converter#141]
**Describe the bug**
Multiple birth was implemented such that if the multiple births integer is present and N is set as indicator, parser assumes that deceased is true, and a .multipleBirthInteger is created.

However, the desired behavior is:

```
BOOL || NUMBER = Answer
-----------------------------
Y + number = integer number
N + number = N
Y + blank = Y
N + blank = N
blank + number = number   << in this case assume the number is meaningful data
blank + blank = nothing
```

**To Reproduce**
Use the value for boolean | number:  `|N|16|'

**Expected behavior**
This should produce ``` "multipleBirthBoolean": false```

**Comment by LisaWellman** [comment]
In Release 1.0.9
