### ISSUE TITLE
Capture Drivers License from PID 20 in ID section

### ISSUE THREAD

**Issue by cragun47** [LinuxForHealth/hl7v2-fhir-converter#143]
The Drivers License information in PID.20.1 should be put in the ID section.

Ignore the state / country / expiration.  Capture only the number:

Example:
```json
{
        "type": {
          "coding": [ {
            "system": "http://terminology.hl7.org/CodeSystem/v2-0203",
            "code": "DL",
            "display": "Driver's license number"
          } ]
        },
        "value": "D-12445889-Z"
      } 
```

Currently capture only the value.  If State and Expiration are required, will look at it in the future.

**Comment by LisaWellman** [comment]
In Release 1.0.9
