### ISSUE TITLE
Graceful fall-back handling of imperfect codable concepts

### ISSUE THREAD

**Issue by cragun47** [LinuxForHealth/hl7v2-fhir-converter#166]
**Describe the bug**
Incoming data can be messy.  Especially race encoding has missing values, assumed encoding schemes, and presumed encoded values.  The system should fall-back to a best case encoding and not destroy the original input.

**To Reproduce**
See samples below of incomplete CWE's and how they should be handled.  Currently using them will produce inconsistent or missing results.

**Expected behavior**
Details of what should happen:

`|2106-3^WHITE^CDCREC|` should produce.
```json
{
        "url": "http://ibm.com/fhir/cdm/StructureDefinition/local-race-cd",
        "valueCodeableConcept": {
          "coding": [ {
            "system": "http://terminology.hl7.org/CodeSystem/v3-Race",
            "code": "2106-3",
            "display": "White"
          } ],
          "text": "WHITE"
        }
      }
```
Because:  CDCREC is a known system, 2106-3 is a valid code in that system, display is looked up in the system as White; the custom text WHITE is kept from the original CWE.2 Value as Text.

`|White^WHITE^L|` should produce.
```json
{
        "url": "http://ibm.com/fhir/cdm/StructureDefinition/local-race-cd",
        "valueCodeableConcept": {
          "coding": [ {
            "system": "urn:id:L",
            "code": "White",
            "display": "WHITE"
          } ],
          "text": "WHITE"
        }
      }
```
Because:  L is and unknown system, White is a supposedly valid code in that system, display: WHITE is kept from CWE.2 as display Value;  text uses display value

`|2106-3^^CDCREC|` should produce.
```json
{
        "url": "http://ibm.com/fhir/cdm/StructureDefinition/local-race-cd",
        "valueCodeableConcept": {
          "coding": [ {
            "system": "http://terminology.hl7.org/CodeSystem/v3-Race",
            "code": "2106-3",
            "display": "White"
          } ],
          "text": "White"
        }
      } 
```
Because:  CRCREC is valid system, 2106-3 is a valid code, display: White is looked up in system for display Value;  because CWE.2 is empty, text uses calculated display.

`|5234-5^hobbit^CDCREC|` invalid code with valid system should produce:
```json
{
        "url": "http://ibm.com/fhir/cdm/StructureDefinition/local-race-cd",
        "valueCodeableConcept": {
          "coding": [ {
         "system":  "system": "http://terminology.hl7.org/CodeSystem/v3-Race",
          "display": "Invalid input: code: 5234-5 for system:  "http://terminology.hl7.org/CodeSystem/v3-Race" original display: hobbit";
          } ]
        }
      }
```
Because:  CRCREC is valid system, 2186-5 is an invalid code, display:  no display value can be found;  because CWE.2 is empty, and no display to use as backup,  text is empty and therefore not shown.

**Additional context**
  Display value is calculated:
      1.  If code is in system-known-to-FHIR, use that display value.getValue
       2.  Otherwise, if code is not in system-known-to-FHIR, it's a bad code, put an error message in the display string
       3.  Otherwise if the system is known-to-us (in CodingSystemMapping ), then we can't tell if the code is valid or not, use the original display text

**Comment by cragun47** [comment]
This was added in https://github.com/LinuxForHealth/hl7v2-fhir-converter/pull/169

**Comment by LisaWellman** [comment]
In Release 1.0.10
