### ISSUE TITLE
Introduce HL7CONVERTER_CONFIG_HOME environment variable

### ISSUE THREAD

**Issue by evbaron** [LinuxForHealth/hl7v2-fhir-converter#172]
HL7 Converter Configuration Property Location

The config.properties file location is searched in the following order:

* HL7CONVERTER_CONFIG_HOME environment variable is checked first
 (environment variable can be set on a docker to manage external config.properties)
* hl7converter.config.home system property is checked next 
   
   ``` -Dhl7converter.config.home=/opt/converter/config_home_folder/```

* Lastly, the local classpath resource folder will be searched for config.properties

**Comment by LisaWellman** [comment]
In Release 1.0.10
