### ISSUE TITLE
Add support for version field and alternate encoding for fallback CWEs

### ISSUE THREAD

**Issue by cragun47** [LinuxForHealth/hl7v2-fhir-converter#173]
**Describe the bug**
Fallback CWEs don't currently support version field or the alternate encoding.

**To Reproduce**
Create a CWE with a version and alternate code/display/system

**Expected behavior**
A CWE with a version should be displayed in the output.
A CWE with alternate encoding should be processed with same fallback logic as the primary encoding.

**Comment by LisaWellman** [comment]
In Release 1.0.10
