### ISSUE TITLE
CWE edge cases produce wrong text

### ISSUE THREAD

**Issue by cragun47** [LinuxForHealth/hl7v2-fhir-converter#184]
**Describe the bug**
Text is incorrectly showing display text, not original text.
Text is sometimes showing error information. 

**To Reproduce**
Marriage and religion are incorrectly putting the display text in the text and not preserving the original text.

**Expected behavior**
Text should contain original text, not coding display text
Coding display text should match display from code + system
Error information should be in display value, when the code is wrong for the system

**Additional context**

**Comment by LisaWellman** [comment]
In Release 1.0.11
