### ISSUE TITLE
Add support for diagnosis  (DG1) and problem (PRB) HL7 segments.

### ISSUE THREAD

**Issue by xpander53** [LinuxForHealth/hl7v2-fhir-converter#198]
Add support for diagnosis  (DG1) and problem (PRB) HL7 segments.
DG1 support will be added for ADT-A01, ADT-A03, ADT-A04, ADT-A08, ORM-O01, ADT-A28, and ADT-A31 messages.
PRB support will be added for PPR_PC1, PPR_PC2, and PPR_PC3 messages.

**The following mappings will be made for DG1:**
DG1-3 to Condition.code.
DG1-5 to Condition.onsetDateTime
DG1-6 to Encounter.diagnosis.use. Being done in #665
DG1-15 to Encounter.diagnosis.rank
DG1-16 to Condition.asserter
DG1-19 to Condition.recordedDate
DG1-20 to Condition.identifier
    DG1.20.1 to Identifier.value. DG1.20.2 to Identifier.system
    DG1.20.3 to Identifier.value. DG1.20.4 to Identifier.system
Condition.category to encounter-diagnosis

**The following mappings will be made for PRB:**
PRB-2 to Condition.recordedDate
PRB-7 to Condition.extension as assertedDate
PRB-9 to Condition.abatementDateTime
PRB-13 to Condition.verificationStatus
PRB-14 to Condition.clinicalStatus.
PRB-17 to Condition.onsetString

**Comment by LisaWellman** [comment]
In Release 1.0.11
