### ISSUE TITLE
Improve support for OBX

### ISSUE THREAD

**Issue by cragun47** [LinuxForHealth/hl7v2-fhir-converter#206]
**Describe the bug**
Many parts of OBX are complete, but there are gaps.
This issue adds support for:
CWE type records
Ranges with only a maximum value
Performer, referenced to both Practitioner and Organization
New resource Practitioner
Additional Performing Organization details such as ContactPoint
New resource ContactPoint
Support for Device
New resource Device

**Expected behavior**
Missing support identified above should be supported for OBX

**Comment by cragun47** [comment]
Support added as described above

**Comment by LisaWellman** [comment]
In Release 1.0.11
