### ISSUE TITLE
resourceType: Patient identifier/type/text removed when it needs to be present.

### ISSUE THREAD

**Issue by CyloNox** [LinuxForHealth/hl7v2-fhir-converter#212]
Hi,

Upon upgrading from 1.0.7 to 1.0.10 the patient resource got altered enough to where a major lookup portion in the identifier segment is no longer useable thus creating all sort of issues (duplicates, not updating, etc..)

**### The main problem and fix:**
_**file**: src/main/resources/hl7/datatype/CodeableConcept.yml_
 I had to remove the condition "**$hideText NULL**" within the text element because it was completely removing that element when it is a valid entry in HL7 and to our system that has multiple MRN's.  By doing this at the very least I'll have that information populated and I can use it to do look up logic correctly for updates and inserts with the proper MRN name reference but without it my patient information becomes useless.

**### A Minor problem and fix:**
_**file**: src/main/java/io/github/linuxforhealth/hl7/data/SimpleDataValueResolver.java_
The information regarding the coding segment didn't look right for the patient and it also didn't provide enough information as to why it failed and what went wrong. So I put in a logic block for our organization that would "**return null**" in the "**private static final SimpleCode commonCodingSystemV2**" to prevent that from showing in the bundle.

**### Example of what it would look like in version 1.0.7 (& with my major and minor fix)**
HL7 PID Segment: 
`PID|1||A100071402^^^^AMRN~B57545903^^^&BMRNroot&ISO^BMRN~C105460^^^&&ISO^CMRN~D2403544^^^DMRN&&ISO^DMRN||TEST^ARRIVE||19680623|M|||^^^^^USA^P|||||||||||||||||||N||||`
FHIR Patient Identifier Segment:
`"identifier": [
	{
		"type": {
			"text": "AMRN"
		},
		"value": "A100071402"
	},
	{
		"type": {
			"text": "BMRN"
		},
		"value": "B57545903"
	},
	{
		"type": {
			"text": "CMRN"
		},
		"value": "C105460"
	},
	{
		"type": {
			"text": "DMRN"
		},
		"value": "D2403544"
	}
]`

**### Example of what it would look like in version 1.0.10**
HL7 PID Segment: 
`PID|1||A100071402^^^^AMRN~B57545903^^^&BMRNroot&ISO^BMRN~C105460^^^&&ISO^CMRN~D2403544^^^DMRN&&ISO^DMRN||TEST^ARRIVE||19680623|M|||^^^^^USA^P|||||||||||||||||||N||||`
FHIR Patient Identifier Segment:
`"identifier": [
	{
		"type": {
			"coding": [
				{
					"system": "http://terminology.hl7.org/CodeSystem/v2-0203",
					"display": "Invalid input: code 'AMRN' could not be mapped to values in system 'http://terminology.hl7.org/CodeSystem/v2-0203' with original display 'null' and version 'null'."
				}
			]
		},
		"value": "A100071402"
	},
	{
		"type": {
			"coding": [
				{
					"system": "http://terminology.hl7.org/CodeSystem/v2-0203",
					"display": "Invalid input: code 'BMRN' could not be mapped to values in system 'http://terminology.hl7.org/CodeSystem/v2-0203' with original display 'null' and version 'null'."
				}
			]
		},
		"value": "B57545903"
	},
	{
		"type": {
			"coding": [
				{
					"system": "http://terminology.hl7.org/CodeSystem/v2-0203",
					"display": "Invalid input: code 'CMRN' could not be mapped to values in system 'http://terminology.hl7.org/CodeSystem/v2-0203' with original display 'null' and version 'null'."
				}
			],
		},
		"value": "C105460"
	},
	{
		"type": {
			"coding": [
				{
					"system": "http://terminology.hl7.org/CodeSystem/v2-0203",
					"display": "Invalid input: code 'DMRN' could not be mapped to values in system 'http://terminology.hl7.org/CodeSystem/v2-0203' with original display 'null' and version 'null'."
				}
			],
		},
		"system": "urn:id:DMRN",
		"value": "D2403544"
	}
]`

If you have anymore questions regarding this, I'd be happy to help and answer them for you but just wanted to point this issue out as it was a major issue when we were testing this out.

Here is a link to a resource that shows the proper output of the identifier segment with coding correctly labeled:
[Fhir Cerner Patient](https://fhir.cerner.com/millennium/dstu2/individuals/patient/ )

**Comment by klwhaley** [comment]
Thank you for drawing our attention to this.  We are looking at a solution.

**Comment by cragun47** [comment]
Code adjusted so that IDs that look up to a valid coding and system, the coding and system are provided, but not text.  FHIR search will still work because the the original code value is in the coding.  Text is unneeded.

When a code does not resolve to the implied system, the type will contain only a text field with the code.

**Comment by cragun47** [comment]
Here is an example:

The following HL7 generates three identifiers. `"PID|1||MRN12345678^^^Regional Health ID^MR~111223333^^^^SS~A100071402^^^^AnUnknownCode|`
The first two are known codings.
The third is an unknown coding.  It has only the text and the value.
```json
        "type": {
          "coding": [ {
            "system": "http://terminology.hl7.org/CodeSystem/v2-0203",
            "code": "MR",
            "display": "Medical record number"
          } ]
        },
        "system": "urn:id:Regional_Health_ID",
        "value": "MRN12345678"
      }, {
        "type": {
          "coding": [ {
            "system": "http://terminology.hl7.org/CodeSystem/v2-0203",
            "code": "SS",
            "display": "Social Security number"
          } ]
        },
        "value": "111223333"
      }, {
        "type": {
          "text": "AnUnknownCode"
        },
        "value": "A100071402"
      } ],

```

**Comment by LisaWellman** [comment]
In Release 1.0.11

**Comment by CyloNox** [comment]
Even in the first example, it's important to show the text because the text represents the alias of what that healthcare system calls the medical record number. Some use BMRN, EMRN, SHHMRN, etc...  The point being that most medical centers will need to know that alias to map.  Thank you for the feedback and information, I'll test out the new version and comment back if I find anything else.

**Comment by CyloNox** [comment]
I can confirm with some additional testing on my end this worked!
