### ISSUE TITLE
Will support for Java 8 end?

### ISSUE THREAD

**Issue by CyloNox** [LinuxForHealth/hl7v2-fhir-converter#231]
**Describe the bug**
Once the upgrade happened from 1.8 to 11 ( [Link to change](https://github.com/LinuxForHealth/hl7v2-fhir-converter/commit/daee82477c4d1881e268d9ad0ec225b3a764a507) ) changes that have occurred in the java files are 11 specific meaning the project as a whole won't compile in a 1.8 capacity. 

**To Reproduce**
To be more specific a change like this one is 10+ ([Link to change](https://github.com/LinuxForHealth/hl7v2-fhir-converter/commit/daee82477c4d1881e268d9ad0ec225b3a764a507#diff-285f6759cc8b83d0701675861ab166d2cdc1f8832d7fcb3d43da58ada26cd781R98)) and will fail to compile in 1.8

**Expected behavior**
perhaps a branch for 1.8 support or a description of explaining where the last commit happened for 1.8

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: [windows] 
 - Version [java 1.8]

**Additional context**
README file might want to change from *JDK 1.8 or Later to *JDK 11 or later (link to last commit for JDK 1.8)

**Comment by LisaWellman** [comment]
The change to use "var" was an inadvertent commit that will be reversed shortly.
The intent was not to require a more recent Java version, but it is a valid point to ensure the requirements are correct and development is being done on the stated version.

**Comment by LisaWellman** [comment]
@CyloNox we do plan to change the project to use Java 11 relatively soon, as Java 8 is in extended support and has some security concerns.  Exact timing TBD, but likely in the next month, and after the next release build.  We will update the README, thank you for bringing this to our attention.

There are no specific plans to use Java 11 features, but of course once this change is made changes could be made that require Java 11.

**Comment by LisaWellman** [comment]
Updated to Java 11 in Release 1.0.13
