### ISSUE TITLE
Ordering of the output in the FHIR Bundle changed

### ISSUE THREAD

**Issue by CyloNox** [LinuxForHealth/hl7v2-fhir-converter#242]
**Describe the bug**
In previous versions the template ordered the resource types in the following order: 
- Patient / Encounter / Organization / Observations / Diagnostic Report / Specimen 

The current output of the bundle now produces this output:
- Observations / Organization / Diagnostic Report / Specimen / Patient / Encounter

**To Reproduce**
Just output any long ORU message

**Expected behavior**
The resourceType ordering to remain the same (with additional types to be documented or noted in the [template.md](https://github.com/LinuxForHealth/hl7v2-fhir-converter/blob/master/TEMPLATING.md)

**Screenshots**
n/a

**Desktop (please complete the following information):**
 - OS: windows
 - Version jdk 1.8, scala 2.12 gradle 1.4.9

**Additional context**
Before the most recent updates the order did have Patient in the beginning with encounter just at the end.  Is this to be expected in the future or will the order of the output be set in stone?

**Comment by LisaWellman** [comment]
The order of resources in the bundle is not defined, and could change.
