### ISSUE TITLE
Remove "urn:uuid:" from UUIDs so they validate with FHIR validator

### ISSUE THREAD

**Issue by cragun47** [LinuxForHealth/hl7v2-fhir-converter#319]
**Describe the bug**
UUIDs of form "urn:uuid:<anything>" now fail in the latest [FHIR validator](http://hl7.org/fhir/validator/).
```
"severity" : "error",
  "code" : "structure",
  "details" : {
   "text" : "UUIDs must be valid"
  },
  "expression" : ["Bundle.entry[0].fullUrl"]
```

**To Reproduce**
Run any current output of the converter through the FHIR validator.

**Expected behavior**
UUIDs should validate

**Comment by LisaWellman** [comment]
In Release 1.0.13
