### ISSUE TITLE
Add support for segment RXA - Pharmacy/Treatment Administration

### ISSUE THREAD

**Issue by jgrant22** [LinuxForHealth/hl7v2-fhir-converter#359]
**Describe the bug**
Add support for pharmacy HL7 segments so the converter can handle support of these segments 

**Expected behavior**
 RXA-7.3 creates a sourceQuantity.System 
 RXA-10 creates a Provider 
 Immunization manufacturer  creates a reference; 
 Provider suffix is mapped 
 RXA-19 to Immunization.reasonCode
 RXA-22 to Immunization.recorded
 Immunization.status is created and maps correctly 
 Immunization.statusReason is created and maps correctly

**Comment by LisaWellman** [comment]
In Release 1.0.14
