### ISSUE TITLE
Unable to read in message templates on Windows platform

### ISSUE THREAD

**Issue by srcarrier** [LinuxForHealth/hl7v2-fhir-converter#38]
On the Windows platform, the **ADT_A01.yml** file is attempted to be read in via the hl7 ResourceReader as "\hl7\message\ADT_A01.yml" _(backward slash instead of forward)_. The file is not found and is thus not getting read in.
We suspect that this is due to the use of the java.io.File object on the Windows platform, in which the platform-dependent path separator is the backward slash instead of forward slash.
The message templates may need to get read in a little differently for this operation to function properly on a Windows platform.

This issue was reported by @ibmatc

**Comment by dixonwhitmire** [comment]
@pbhallam - I have a Windows 10 laptop that's ready to go. I'll be happy to take a look at this one as well.
