### ISSUE TITLE
add mappings to Immunization from OBX

### ISSUE THREAD

**Issue by jgrant22** [LinuxForHealth/hl7v2-fhir-converter#400]
- Immunization.reaction.detail when OBX.3 is 31044-1 (Immunization reaction)
  - Immunization.programEligibility (CodeableConcept) when OBX-3=64994-7 (Vaccine funding program eligibility category)
  - Immunization.fundingSource (CodeableConcept) when OBX-3=30963-3 (Funds vaccine purchased with VAERS)
  - Immunization.education(PresentationDate when OBX-3=29769-7 , PubicationDate when OBX-3=29768-9,   and documentType when OBX-3=69764-9)
  - Immunization.statusReason(MEDPROC when OBX-3=30945-0 (Vaccination contraindication/precaution)IMMUNE when OBX-3=59784-9 (Disease with presumed immunity))

**Comment by cragun47** [comment]
Completion of this issue is waiting on #414, which is a bug discovered completing this item.

We will mark this one complete for everything else and #414 will complete that particular case.

**Comment by LisaWellman** [comment]
In release 1.0.15
