### ISSUE TITLE
Add runtime properties; add tenant prepend for organization identifier 

### ISSUE THREAD

**Issue by cragun47** [LinuxForHealth/hl7v2-fhir-converter#403]
Organization identifier needs an option to prepend a tenant id.
If the tenant id is provided the organization identifier value should be `<tenantid>` + `period` +  `IN1.3.1`

This requires a new method to pass parameters at run time.
A new method is added on options object.
A string property expressed as a key / value pair.  Properties become available as variables to the templates.  A property `TENANT` with value `myTenantId` is utilized in templates as `$TENANT`.             | options.withProperty("TENANT","myTenantId")

Example added during creation of the options:
`ConverterOptions customOptionsWithTenant = new Builder().withValidateResource().withPrettyPrint().withProperty("TENANT", "TenantId").build();`

**Comment by LisaWellman** [comment]
In release 1.0.16
