### ISSUE TITLE
Add support for IN2, additional mappings for IN1

### ISSUE THREAD

**Issue by cragun47** [LinuxForHealth/hl7v2-fhir-converter#411]
Add additional fields for Coverage / RelatedPerson from IN2 record.

 IN2.2 (SSN) to RelatedPerson.identifier 
 IN2.63 to RelatedPerson.telecom

 IN2.72 as backup relationship for IN1.17.
 NOTE: special rules apply for interpreting the _direction_ of the relationship as input and mapping to the _direction_ of the relationship expected by the FHIR field.
 
 Interested parties should read detailed notes in v2ToFhirMapping.yml `IMPORTANT NOTES ON RELATIONSHIP MAPPINGS`

- Coverage.identifier from IN2-6 
    - Coverage.identifier.type:
        system= http://terminology.hl7.org/CodeSystem/v2-0203
        code=MC
        display=Patient's Medicare number
- Coverage.identifier from IN2-8  
    - Coverage.identifier.type:
        system= http://terminology.hl7.org/CodeSystem/v2-0203
        code=MA
        display=Patient Medicaid number
-  Coverage.identifier from IN2-61 which will take precedence over IN1-36.  
    - Coverage.identifier.type:
         code='MB'
         display='Member Number'
         system='http://terminology.hl7.org/CodeSystem/v2-0203'
 - IN1.35 to Organization.identifier. This identifier will have a value only, no system or type. (PR A)
- Coverage.payor create a separate Organization from IN2.25
  - IN2.25.1 is used to set Organization.id.
     - If a tenant is set, the id value should be <tenant>.<IN2-25.1>
     - If a tenant is not set, the id value will be just IN2-25.1
 - Organization.identifier using
 ```
 .1 identifier.value
 .4 identifier.system (urn:id:25.4)
 .5 identifier.type.code
 .7 identifier.period.start
 .8 identifier.period.end
```
- Organization.name using IN2.25.1 identifier.value. **BJC: current code requires a name. L4H Converter Issue 422 will remove this requirement in the future.**
  Coverage.policyHolder create a separate Organization from IN2.69
 - IN2.69.10 is used to set Organization.id.
    - If a tenant is set, the id value should be <tenant>.<IN2-69.10>
    - If a tenant is not set, the id value will be just IN2-69.10
 Organization.identifier using
 ```
 .10 identifier.value
 .6 identifier.system (urn:id:69.6)
 .7 identifier.type.code
 IN2.69.1 is used to set Organization.name
```
 
 RelatedPerson should only be created when the subscribed is a relative.  (Not an employer)
 
 Patient.identifier from IN1.49

if subscriber=self, use IN2.2 as fallback to populate SSN patient identifier if PID-19 is empty

IN2.6 to Patient.identifier.type.coding.code=MC

IN2.8 to Patient.identifier.type.coding.code=MA

If subscriber=self, use IN2-61 for Patient.identifier.type.coding.code=MB, fallback to IN1-36:

**Comment by LisaWellman** [comment]
In release 1.0.16
