### ISSUE TITLE
Partial support for OML_O21 messages

### ISSUE THREAD

**Issue by lisadier** [LinuxForHealth/hl7v2-fhir-converter#416]
We received a contribution from @hajiratasneem to add OML_O21 support.  
I have updated and tweaked that contribution to enhance and clarify the level of OML_O21 message support:

- Removed unused segments SPM and DG1 from both DiagnosticReport resources in OML_O21.yml
- Updated grouping on the Specimen resource so that a link is properly created in the DiagnosticReport
- Fixed grouping on the NTE segments
- Added AL1 support
- Added necessary unit tests to boost coverage of critical scenarios
- Simplified the message content in the tests to focus on the message-level resource testing
- Added asserts to ensure that no ‘extra’ resources are created
- Updated asserts to check for all expected resources
- Discovered that ServiceRequests are not created for ORC segments unless an OBR is provided.
- Discovered that only one ORDER group is supported per message. The HL7 message definition allows the ORDER group to be repeatable but the converter (and parser) do not support multiple ORDER groups.
- Discovered that PID must be provided in OML_O21 messages to avoid FHIR validation errors, even though the HL7 message definition doesn’t require PID. The patient (from PID) is required for ServiceRequest and Condition FHIR resources to be valid.
- Discovered that OBX support was not contributed and is not included.
- Updated documentation to indicate partial support for OML_O21, with notes about above limitations that were discovered.

**Comment by lisadier** [comment]
Related PRs:
https://github.com/LinuxForHealth/hl7v2-fhir-converter/pull/257
https://github.com/LinuxForHealth/hl7v2-fhir-converter/pull/413

**Comment by LisaWellman** [comment]
In release 1.0.16
