### ISSUE TITLE
Support Immunization.education structures

### ISSUE THREAD

**Issue by cragun47** [LinuxForHealth/hl7v2-fhir-converter#449]
Immunization.education structures need to be created from separate sibling OBX records that are related though a group number in OBX.4 of each record.   

A general solution to this was attempted in #414.  No other needs for the function were found.

So, this is a specific solution for Immunization.education.  It is relatively small and specific.  It uses parsed structure objects to look through the message groups and segments to locate and evaluate the sibling OBXs.  It can serve as a future model for other situations where repeating sibling segments must be considered.

Added testing so that multiple groups of RXA components with their own set of OBX records are evaluated separately with no data bleed.

**Comment by LisaWellman** [comment]
In release 1.0.18
