### ISSUE TITLE
Support for ADT^A01, ^A03, ^A04, ^A08, ^A28, ^A31; including IN1/IN2

### ISSUE THREAD

**Issue by cragun47** [LinuxForHealth/hl7v2-fhir-converter#463]
Support for ADT^A01, ^A03, ^A04, ^A08, ^A28, ^A31 messages; 
Extend support for IN1/IN2 to these messages.

Support for ADT^A01, ^A03, ^A04, ^A08, ^A28, ^A31 means: segments MSH, EVN, PID, PD1, PV1, PV2, OBX, Al1, DG1, PR1, IN1, IN2.
Other segments may be added to these and other messages in the future.

**Comment by LisaWellman** [comment]
In release 1.0.18
