### ISSUE TITLE
How to use latest alpha release?

### ISSUE THREAD

**Issue by kesavkolla** [LinuxForHealth/hl7v2-fhir-converter#47]
The latest release of 1.0.3-alpha doesn't seem to be available from mvnrepository. Is there any specific repository location should I add in my pom.xml?

**Comment by srcarrier** [comment]
@pbhallam or @dixonwhitmire - do you know when the `1.0.3-alpha` release will be published in mvn?

**Comment by dixonwhitmire** [comment]
@srcarrier and @kesavkolla - We should be able to upload the new release tomorrow. I'll meet with @pbhallam to review the current release process.

**Comment by dixonwhitmire** [comment]
@srcarrier @kesavkolla - the new release is available. Thanks
