### ISSUE TITLE
Generated ids for FHIR resources will start with a timestamp

### ISSUE THREAD

**Issue by klwhaley** [LinuxForHealth/hl7v2-fhir-converter#482]
Previously created FHIR resources had an id of a UUID.

With this change the resources created will have an id of CURRENT_NANOSECOND.UUID

e.g. "id": "1657728387907169000.77b74dd5-4f15-4b22-b8a2-8aaf4617d8d0",

This id starting with a timestamp representation will aid in FHIR performance for indexing/search.

**Comment by LisaWellman** [comment]
In Release 1.0.19
