### ISSUE TITLE
Java compile error - data\Hl7RelatedGeneralUtils.java:162: error: unknown tag: current      * Format is <current nano second>.<UUID>.

### ISSUE THREAD

**Issue by youngmin-master** [LinuxForHealth/hl7v2-fhir-converter#495]
**Describe the bug**
During initial installation using gradle, it gives the following error:
![image](https://user-images.githubusercontent.com/122579958/212225969-fcd1fcd0-ffa5-462a-b9da-005ebc774dbf.png)

**To Reproduce**
Run gradlew build in the downloaded directory, for example,
Downloads\hl7v2-fhir-converter-master\hl7v2-fhir-converter-master>gradlew build

**Expected behavior**
The error should not occur and the installation should be run without an error.

**Screenshots**
Pls refer to the image file above in problem description.

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] Windows 10
![image](https://user-images.githubusercontent.com/122579958/212226318-dc3df850-10c9-4d57-b665-a3606467606c.png)

**Additional context**

**Comment by LisaWellman** [comment]
This should not prevent your build from succeeding - can you confirm that your build is succeeding?
Agree the javadoc issues should be cleaned up at some point.

**Comment by LisaWellman** [comment]
Fixed under https://github.com/LinuxForHealth/hl7v2-fhir-converter/pull/501

**Comment by LisaWellman** [comment]
In release 1.1.0
