### ISSUE TITLE
Is this still active?   

### ISSUE THREAD

**Issue by healthcaredigitaltwin** [LinuxForHealth/hl7v2-fhir-converter#502]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by LisaWellman** [comment]
Yes, the project is still available and we welcome contributions.

**Comment by JFisk42** [comment]
@LisaWellman is this still true? My team has been maintaining a [fork](https://github.com/CDCgov/hl7v2-fhir-converter/) of this repo and the issue of long term care was brought up. If this repo is still active then it is also a question of capacity. We've added a handful of changes ([diff here](https://github.com/LinuxForHealth/hl7v2-fhir-converter/compare/master...CDCgov:hl7v2-fhir-converter:master)) and are also wanting to update a number of the dependencies to reduce potential vulnerabilities. Is that something that would be viable?

**Comment by LisaWellman** [comment]
I think we'd consider adding additional owners as current owners are not actively contributing
