### ISSUE TITLE
Help with config.properties

### ISSUE THREAD

**Issue by billharty** [LinuxForHealth/hl7v2-fhir-converter#509]
Trying to build a simple Java/Spring/Maven app using Linxux4Health v2 to fhir converter (Java 20, Spring 3.1.4).  Got it working using default templates, but as soon as I put a config.properties file in place, I get the following error: 

```
There was a problem parsing the message; Failure to initialize the templates for the converter.
Error when creating PropertyDescriptor for public final void org.apache.commons.configuration2.AbstractConfiguration.setProperty(java.lang.String,java.lang.Object)! Ignoring this property.

```
The config.properties file looks like this:

```
base.path.resource=/opt/converter/resources
supported.hl7.messages=ADT_A01, ADT_A03, ADT_A04, ADT_A08, ADT_A28, ADT_A31, ADT_A34, ADT_A40, DFT_P03, MDM_T02, MDM_T06, OML_O21, ORM_O01, OMP_O09, ORU_R01, PPR_PC1, RDE_O11, RDE_O25, VXU_V04
default.zoneid=+08:00

```

/opt/converter/resources contains two folders: /fhir and /hl7 which are copies from your repo.  I am hoping to customize templates within those folders.
I also tried putting the templates in the resource folder under the class path, and I get the same error.   

Thanks for any guidance/help.  Also, please let me know if there is a better way to ask for help with issues like this as opposed to opening a ticket.

**Comment by LisaWellman** [comment]
Does the error occur only when you specify a value for base.path.resource?  In other words, if you specify no value
`base.path.resource=`
does the error go away?  To take one step at a time, the file that works for me is
```
base.path.resource=
supported.hl7.messages=ADT_A01, ADT_A03, ADT_A04, ADT_A08, ADT_A28, ADT_A31, ADT_A34, ADT_A40, DFT_P03, MDM_T02, MDM_T06, OML_O21, ORM_O01, OMP_O09, ORU_R01, PPR_PC1, RDE_O11, RDE_O25, VXU_V04
default.zoneid=+08:00
additional.conceptmap.file=
additional.resources.location=
```

**Comment by billharty** [comment]
Hi Lisa, thanks for the response.  We decided to move on to another approach/engine, so this ticket can be closed out.  Thanks anyway.


From: Lisa Wellman ***@***.***>
Date: Monday, November 20, 2023 at 9:59 AM
To: LinuxForHealth/hl7v2-fhir-converter ***@***.***>
Cc: Bill Harty ***@***.***>, Author ***@***.***>
Subject: Re: [LinuxForHealth/hl7v2-fhir-converter] Help with config.properties (Issue #509)

Does the error occur only when you specify a value for base.path.resource? In other words, if you specify no value
base.path.resource=
does the error go away? To take one step at a time, the file that works for me is

base.path.resource=

supported.hl7.messages=ADT_A01, ADT_A03, ADT_A04, ADT_A08, ADT_A28, ADT_A31, ADT_A34, ADT_A40, DFT_P03, MDM_T02, MDM_T06, OML_O21, ORM_O01, OMP_O09, ORU_R01, PPR_PC1, RDE_O11, RDE_O25, VXU_V04

default.zoneid=+08:00

additional.conceptmap.file=

additional.resources.location=
