### ISSUE TITLE
Invalid content in meta.source for fhir bundle

### ISSUE THREAD

**Issue by ibmatc** [LinuxForHealth/hl7v2-fhir-converter#56]
When using the provided HL7 data to convert to FHIR, the resulting FHIR contains an invalid meta.source value:

```
		"source": "Message: ADT_A01, Message Control Id: 102"
```

To simplify I switched to only this for input HL7 data:
`MSH|^~\\&|SE050|050|PACS|050|||ADT^A01|102|T|2.6|||AL|NE\r`

The resulting entire bundle is:
```
{
	"resourceType": "Bundle",
	"id": "2dd486aa-7062-45e8-acd8-5fc274afc88d",
	"meta": {
		"lastUpdated": "2021-02-15T16:07:10.203-06:00",
		"source": "Message: ADT_A01, Message Control Id: 102"
	},
	"type": "collection"
}

```

This fhir bundle sent to the $validate API of a FHIR server results in the following error message:

```
{
    "resourceType": "OperationOutcome",
    "issue": [
        {
            "severity": "fatal",
            "code": "invalid",
            "details": {
                "text": "FHIRProvider: Uri value: 'Message: ADT_A01, Message Control Id: 102' must not contain whitespace [Bundle.meta]"
            },
            "expression": [
                "Bundle.meta"
            ]
        }
    ]
}
```

I have not dug into the meaning of the data passed in enough to understand whether it's in the wrong field or invalidly converted to FHIR, but the validate API indicates it is not correct as-is.

**Comment by pbhallam** [comment]
Source is suppose to be a URI, I will fix that.

**Comment by pbhallam** [comment]
Merged changes.
