### ISSUE TITLE
Message header conversion

### ISSUE THREAD

**Issue by mohdimranqureshi** [LinuxForHealth/hl7v2-fhir-converter#59]
Can you guys please add the mapping to convert the MSH segment of the HL7 message? 

@dixonwhitmire @pbhallam

**Comment by dixonwhitmire** [comment]
@pbhallam is this a change we can accommodate.

**Comment by pbhallam** [comment]
Adding support for Message header: 
Required MSH fields are: MSH-24.2, MSH-9.2, MSH-10
{
  "resourceType": "Bundle",
  "id": "8dd42b1c-9ae4-44f1-af2c-1df1b3b23f32",
  "meta": {
    "lastUpdated": "2021-03-16T11:58:20.624+08:00"
  },
  "type": "collection",
  "entry": [ {
    "fullUrl": "urn:uuid:MessageHeader/0c83d2e5-3db4-3ac0-a118-20fa1d836d3a",
    "resource": {
      "resourceType": "MessageHeader",
      "id": "0c83d2e5-3db4-3ac0-a118-20fa1d836d3a",
      "eventCoding": {
        "system": "http://terminology.hl7.org/CodeSystem/v2-0003",
        "code": "A01",
        "display": "ADT/ACK - Admit/visit notification"
      },
      "destination": [ {
        "name": "New Tester",
        "endpoint": "MS"
      } ],
      "source": {
        "name": "Amalga HIS",
        "endpoint": "4086::132:2A57:3C28"
      },
      "reason": {
        "coding": [ {
          "system": "http://terminology.hl7.org/CodeSystem/message-reasons-encounter",
          "code": "admit",
          "display": "Admit"
        } ]
      }
    }
  } ]
}

**Comment by mohdimranqureshi** [comment]
Thanks, @pbhallam to add the support for message header segment.
