### ISSUE TITLE
HL7 Message Template for FHIR Medication Resource

### ISSUE THREAD

**Issue by dixonwhitmire** [LinuxForHealth/hl7v2-fhir-converter#72]
Add support to the converter for the FHIR medication resource.

Documentation:

- [Medicate Resource Overview](https://www.hl7.org/fhir/medication.html)
- [Medication HL7 v2 Mapping](https://www.hl7.org/fhir/medication-mappings.html#v2)
- [Converter documentation](https://github.com/LinuxForHealth/hl7v2-fhir-converter/blob/master/README.md)

**Comment by LisaWellman** [comment]
Closing this with the work done.  Further enhancements will be made in a new issue
