### ISSUE TITLE
DiagnosticReport.status: minimum required =1, but only found 0 when validating HL7 ORU-R01 message.

### ISSUE THREAD

**Issue by claverols** [LinuxForHealth/hl7v2-fhir-converter#90]
**Describe the bug**
Error: "DiagnosticReport.status: minimum required = 1, but only found 0 (from http://hl7.org/fhir/StructureDefinition/DiagnosticReport)" shows when running the current FHIR validator on the converted file from attached HL7 message. 

**To Reproduce**
Run attached HL7 message within latest FHIR validator available and check the output for errors.

**Expected behavior**
The HL7 message
[oru-r01-sample01.txt](https://github.com/LinuxForHealth/hl7v2-fhir-converter/files/6452132/oru-r01-sample01.txt)
 is missing that field, but should the converter be able to deal with it? (ie. map null to Unknown when the expected value is not found?) rather than throw an error?

pydantic.error_wrappers.ValidationError: 1 validation error for DiagnosticReport
__root__ -> status
  field required (type=value_error.missing)

**Desktop (please complete the following information):**
 - OS: MacOS Big Sur
 - Version 11.2.1

**Additional context**

**Comment by pbhallam** [comment]
@claverols I will look into this.

**Comment by jgrant22** [comment]
I don't think I have power to self assign but I will be looking into this card

**Comment by claverols** [comment]
@jgrant22 The FHIR validator tool gets updated quite often; so 1st thing I would download the latest version available and will try to run the FHIR validation against the JSON you will get when converting from the HL7 message using the current HL7toFHIR converter. 

The location for the FhIR validator is: https://confluence.hl7.org/display/FHIR/Using+the+FHIR+Validator#UsingtheFHIRValidator-Downloadingthevalidator

I run the validator with these parameters (-version 4.0 for FHIR version):
java -jar validator_cli.jar -version 4.0 ./../folder/yourconvertedintoFHIR.json -output  ./../folder/outputfromvalidation.json

Search the output from running the FHIR  validation for the reported error. Please let me know if you need more details.

**Comment by LisaWellman** [comment]
DiagnosticReport.status is a required field (https://www.hl7.org/fhir/diagnosticreport.html) so I would expect it to fail validation if it is not set.  The solution to set this field to unknown (https://www.hl7.org/fhir/valueset-diagnostic-report-status.html) if not in the HL7 message seems correct.

**Comment by cragun47** [comment]
In Release 1.0.8
