### ISSUE TITLE
Conversion of Patient's name prefix and suffix are in the inverted order.

### ISSUE THREAD

**Issue by claverols** [LinuxForHealth/hl7v2-fhir-converter#92]
**Describe the bug**
The converter converts the Patient name's prefix and suffix in the opposite order that it should be (according to the PID segment in HL7)
**To Reproduce**
HL7 segment : PID|1||12345678^^^^MR||Mouse^Mickey^J^III^Mr^^| ...
The order according to the HL7 reference should be : XPN.4 - Suffix and XPN.5 - Prefix
but in the current HL7toFHIR conversion I get in the .json:
Output:
 "name": [
          {
            "family": "Mouse",
            "given": [
              "Mickey"
            ],
            "prefix": [
              "III"
            ],
            "suffix": [
              "Mr"

**Expected behavior**
"Mr" should be the prefix and "III" the suffix.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: MacOS
 - Version Big Sur

**Additional context**

**Comment by cragun47** [comment]
I am working this issue.

**Comment by LisaWellman** [comment]
Change done with PR https://github.com/LinuxForHealth/hl7v2-fhir-converter/pull/93

**Comment by cragun47** [comment]
In Release 1.0.8
