### ISSUE TITLE
map Immunization dosage

### ISSUE THREAD

**Issue by jgrant22** [LinuxForHealth/hl7v2-fhir-converter#95]
Describe the enhancement:
Enhance converter to handle immunization dosage (amount and units)

Expected behavior:
HL7 converter should be able to handle immunization dosage and units

Desktop:
OS: Mac OS
Version Big Sur

**Comment by cragun47** [comment]
In Release [1.0.8](https://github.com/LinuxForHealth/hl7v2-fhir-converter/releases/tag/1.0.8)
